# Generated by Django 3.2.9 on 2022-04-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aim'),
    ]

    operations = [
        migrations.AddField(
            model_name='aim',
            name='taskAim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.task'),
        ),
    ]
